### ISSUE TITLE
Alert data fields

### ISSUE THREAD

**Issue by maciejforcone** [boriskirov/text-string#3]
1. Provide a title of your requested data field. 
Alert reason
Alert status
Alert source

2. Provide an example of the response you'd like to see in your text object.

Alert reason:

CPU usage is {95-100}% in the last 1 min for {hostName}. Alert when > {80-95}%.
CPU usage is 95% in the last 1 min for gke-edge-oblt-edge-oblt-pool-095c801b-o3do. Alert when > 90%.

Failed transactions is {50-100}% in the last 5 mins for {serviceName}. Alert when > {20-50}%.
Failed transactions is 42% in the last 5 mins for opbeans-python. Alert when > 30%.

Load is {90-100} in the last 1 min for {inventoryName}. Alert when > {80-90}.
Load is 3.7 in the last 1 min for gke-edge-oblt-edge-oblt-pool-095c801b-o3do. Alert when > 1.

{metricName} reported no data in the last 1m for all hosts
aws.ec2.cpu.total.pct reported no data in the last 1m for all hosts

Alert status:
Active (badge, color:critical)
Recovered (badge, color:healthy)

Alert source:
{serviceName}
{hostName}
{metricName}
{inventoryName}

4. Describe the solution you'd like
quick generation of example values for above fields in figma.

**Comment by boriskirov** [comment]
Closes #4
